### ISSUE TITLE
Selected and setSelected can't be the same Constant (SDK 49)

### ISSUE THREAD

**Issue by OliverGalusinski** [mmusaib/react-native-dropdown-country-picker#1]
selected is expecting a string while setSelected is expecting "undefined"

**Comment by mmusaib** [comment]
Selected and setSelected are not same constants firstly. They are the react state variable and the state function to update that variable. 

So selected is expecting the state variable or a string. While as setSelected is expecting the function to update that variable.

For more information you can check the following video, to get more clarity.

https://www.youtube.com/watch?v=ZstelmTWhjw&t

**Comment by OliverGalusinski** [comment]
I know what you are saying.
I am aware that it should work like that.
But I am trying to tell you that it doesn't work. I tried to put the variable as selected and the function which updates the variable as setSelected but it throws me an error.

It is complaining that the Variable is a String.

I Provided you with the code:

```ts
export default function (){
    analytics().logAppOpen()
    const [selected, setSelected] = useState('+91');

    return (
            <View style={styles.container}>
                <CountryCodeDropdownPicker selected={selected} setSelected={setSelected} setCountryDetails={}/>
```

And the error:
TS2322: Type 'Dispatch<SetStateAction<string>>' is not assignable to type 'Dispatch<SetStateAction<undefined>>'.   Type 'SetStateAction<undefined>' is not assignable to type 'SetStateAction<string>'.     Type 'undefined' is not assignable to type 'SetStateAction<string>'.

**Comment by mmusaib** [comment]
Hey Oliver,

As I am checking your code, I see that you are passing nothing to the prop setCountryDetails, which expects a setState function.

It is the one throwing the error. If you don't have to use country details, simply don't pass that prop. It will solve the issue.

So, the modified code should look like:

```js
export default function (){
    analytics().logAppOpen()
    const [selected, setSelected] = useState('+91');

    return (
            <View style={styles.container}>
                <CountryCodeDropdownPicker selected={selected} setSelected={setSelected} />
```

**Comment by OliverGalusinski** [comment]
Hey removing setCountryDetails doesn't change the Issue.

To show you my Problem I made a Screenshot just to not confuse you anymore:

<img width="987" alt="Screenshot 2023-08-09 at 01 48 43" src="https://github.com/mmusaib/react-native-dropdown-country-picker/assets/64497107/4daa3257-354d-468d-96c6-564a1eade9ed">

also:

<img width="868" alt="Screenshot 2023-08-09 at 01 50 04" src="https://github.com/mmusaib/react-native-dropdown-country-picker/assets/64497107/8d050955-acc2-414d-801c-d1cad3bae796">

**Comment by mmusaib** [comment]
Have you tried compiling the code. It think it is the warning thrown by eslint for typescript in the IDE or something like that.

I think after compiling it should work perfectly. As the package has around 1k users and no one has raised any complaint like this.
