### ISSUE TITLE
Can't Remove the country Code Through Styles

### ISSUE THREAD

**Issue by EnemyBot3** [mmusaib/react-native-dropdown-country-picker#5]
The country codes (example displayed below) cannot be styled through the provided props.

<img width="266" alt="image" src="https://github.com/user-attachments/assets/22b93e71-0d01-4afa-9c44-b6ef6fbd9baf">

even when using the `countryCodeTextStyles={{display: "none"}}` prop everything but the country code is removed.

<img width="263" alt="image" src="https://github.com/user-attachments/assets/defa9f42-e64d-4cd2-9506-7227658c0682">

**Comment by mmusaib** [comment]
I don't know where you have gone wrong, but instead of the country code in the above image, it should display flag of the selected country.

**Comment by EnemyBot3** [comment]
not sure either, but can you add  prop to hide them

**Comment by mmusaib** [comment]
Sure will add that in the next update
