### ISSUE TITLE
 VirtualizedLists should never be nested inside plain ScrollViews with the same orientation because it can break windowing and other functionality - use another VirtualizedList-backed container instead. [Component Stack]

### ISSUE THREAD

**Issue by tarifalhasan** [mmusaib/react-native-dropdown-country-picker#9]
(NOBRIDGE) ERROR  VirtualizedLists should never be nested inside plain ScrollViews with the same orientation because it can break windowing and other functionality - use another VirtualizedList-backed container instead. [Component Stack]

import { Ionicons } from "@expo/vector-icons";
import { Link } from "expo-router";
import { useState } from "react";
import CountryCodeDropdownPicker from "react-native-dropdown-country-picker";

import {
  Image,
  ScrollView,
  StyleSheet,
  Text,
  TextInput,
  TouchableOpacity,
  View,
} from "react-native";
export default function SignupScreen() {
  const [formData, setFormData] = useState({
    firstName: "",
    email: "",
    brandName: "",
    phoneNumber: "",
    password: "",
  });
  const [showPassword, setShowPassword] = useState(false);
  const [selected, setSelected] = useState("+91");
  const [country, setCountry] = useState("");
  const [phone, setPhone] = useState("");
  const handleSignup = () => {
    console.log("Signup attempted with:", formData);
  };

  return (
    <ScrollView style={styles.container}>
      <Image
        style={styles.leftDecoration}
        source={require("@/assets/images/left_login.png")}
      />
      <Image
        style={styles.rightDecoration}
        source={require("@/assets/images/right_login.png")}
      />
      <Image
        source={require("@/assets/images/logo.png")}
        style={styles.logo}
        resizeMode="contain"
      />
      <View style={styles.content}>
        <View style={styles.headerContainer}>
          <Text style={styles.welcomeTitle}>Welcome to</Text>
          <Text style={styles.portalTitle}>
            <Text style={styles.floorWalk}>FloorWalk</Text>
            {"\n"}
            Shopper Portal
          </Text>
        </View>

        <View style={styles.formContainer}>
          <TextInput
            style={styles.input}
            placeholder="First Name"
            value={formData.firstName}
            onChangeText={(text) =>
              setFormData({ ...formData, firstName: text })
            }
            autoCapitalize="words"
          />

          <TextInput
            style={styles.input}
            placeholder="Email Id"
            value={formData.email}
            onChangeText={(text) => setFormData({ ...formData, email: text })}
            keyboardType="email-address"
            autoCapitalize="none"
          />

          <TextInput
            style={styles.input}
            placeholder="Brand Name"
            value={formData.brandName}
            onChangeText={(text) =>
              setFormData({ ...formData, brandName: text })
            }
            autoCapitalize="words"
          />

          <View style={styles.phoneContainer}>
            <CountryCodeDropdownPicker
              selected={selected}
              setSelected={setSelected}
              setCountryDetails={setCountry}
              phone={phone}
              setPhone={setPhone}
              countryCodeTextStyles={{ fontSize: 13 }}
            />
            <TextInput
              style={styles.phoneInput}
              placeholder="Phone Number"
              value={formData.phoneNumber}
              onChangeText={(text) =>
                setFormData({ ...formData, phoneNumber: text })
              }
              keyboardType="phone-pad"
            />
          </View>

          <View style={styles.passwordContainer}>
            <TextInput
              style={styles.passwordInput}
              placeholder="Password"
              value={formData.password}
              onChangeText={(text) =>
                setFormData({ ...formData, password: text })
              }
              secureTextEntry={!showPassword}
            />
            <TouchableOpacity
              style={styles.eyeIcon}
              onPress={() => setShowPassword(!showPassword)}
            >
              <Ionicons
                name={showPassword ? "eye-outline" : "eye-off-outline"}
                size={24}
                color="#666"
              />
            </TouchableOpacity>
          </View>

          <TouchableOpacity style={styles.signupButton} onPress={handleSignup}>
            <Text style={styles.signupButtonText}>Create Account</Text>
          </TouchableOpacity>
        </View>

        <View style={styles.loginLinkContainer}>
          <Text style={styles.loginLinkText}>Already have an account </Text>
          <Link href={"/Login"}>
            <Text style={styles.loginLink}>Login</Text>
          </Link>
        </View>

        <View style={styles.howItWorks}>
          <Text style={styles.howItWorksTitle}>How It Works</Text>
          <Text style={styles.howItWorksText}>
            Watch this 90 seconds video to know how can FloorWalk help you
            improve your Consumer Experience.
          </Text>
        </View>
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  leftDecoration: {
    width: 70,
    height: 150,
    position: "absolute",
    top: 90,
    left: 0,
  },
  rightDecoration: {
    width: 70,
    height: 150,
    position: "absolute",
    top: 90,
    right: 0,
  },
  content: {
    padding: 20,
  },
  logo: {
    width: 140,
    height: 60,
    marginTop: 24,
    alignSelf: "center",
  },
  headerContainer: {
    paddingVertical: 30,
  },
  welcomeTitle: {
    fontSize: 30,
    color: "#003C5D",
    textAlign: "center",
    fontWeight: "700",
  },
  portalTitle: {
    fontSize: 35,
    textAlign: "center",
    fontWeight: "700",
  },
  floorWalk: {
    color: "#8DC63F",
  },
  formContainer: {
    width: "100%",
    backgroundColor: "#fff",
    padding: 20,
    borderRadius: 10,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  input: {
    width: "100%",
    height: 45,
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 5,
    paddingHorizontal: 15,
    marginBottom: 15,
    fontSize: 14,
  },
  phoneContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 15,
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 5,
  },
  countryPickerButton: {
    paddingHorizontal: 10,
  },
  phoneInput: {
    flex: 1,
    height: 45,
    paddingHorizontal: 15,
    fontSize: 14,
  },
  passwordContainer: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 5,
    marginBottom: 15,
  },
  passwordInput: {
    flex: 1,
    height: 45,
    paddingHorizontal: 15,
    fontSize: 14,
  },
  eyeIcon: {
    padding: 10,
  },
  signupButton: {
    width: "100%",
    backgroundColor: "#0088CC",
    padding: 15,
    borderRadius: 5,
    alignItems: "center",
  },
  signupButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },
  loginLinkContainer: {
    alignItems: "center",
    justifyContent: "center",
    padding: 14,
    flexDirection: "row",
  },
  loginLinkText: {
    fontSize: 14,
    fontWeight: "400",
  },
  loginLink: {
    fontSize: 16,
    fontWeight: "700",
    color: "#0088CC",
  },
  howItWorks: {
    marginTop: 30,
    alignItems: "center",
  },
  howItWorksTitle: {
    fontSize: 20,
    color: "#003366",
    marginBottom: 10,
  },
  howItWorksText: {
    textAlign: "center",
    color: "#666",
    fontSize: 14,
    paddingHorizontal: 20,
  },
});

**Comment by mmusaib** [comment]
You have nested the component inside of ScrollView and it is just a warning.
 It happens because two nested SrollViews may lead to some inefficiency in scrolling. So, that is why this warning is displaying.

**Comment by tarifalhasan** [comment]
How do I fix the issue?
